CREATE TABLE IF NOT EXISTS burrows (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    depth DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    width DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    is_occupied BOOLEAN NOT NULL DEFAULT false,
    age INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_dug_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); 