database:
  host: db
  port: 5432
  user: postgres
  password: postgres
  database: gophernet

scheduler:
  report_interval: 2m
  update_interval: 1m
  max_burrow_age: 1440
  depth_increment_rate: 0.009