// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gophernet/pkg/db/ent/burrow"
	"gophernet/pkg/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BurrowDelete is the builder for deleting a Burrow entity.
type BurrowDelete struct {
	config
	hooks    []Hook
	mutation *BurrowMutation
}

// Where appends a list predicates to the BurrowDelete builder.
func (bd *BurrowDelete) Where(ps ...predicate.Burrow) *BurrowDelete {
	bd.mutation.Where(ps...)
	return bd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bd *BurrowDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bd.sqlExec, bd.mutation, bd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bd *BurrowDelete) ExecX(ctx context.Context) int {
	n, err := bd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bd *BurrowDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(burrow.Table, sqlgraph.NewFieldSpec(burrow.FieldID, field.TypeInt))
	if ps := bd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bd.mutation.done = true
	return affected, err
}

// BurrowDeleteOne is the builder for deleting a single Burrow entity.
type BurrowDeleteOne struct {
	bd *BurrowDelete
}

// Where appends a list predicates to the BurrowDelete builder.
func (bdo *BurrowDeleteOne) Where(ps ...predicate.Burrow) *BurrowDeleteOne {
	bdo.bd.mutation.Where(ps...)
	return bdo
}

// Exec executes the deletion query.
func (bdo *BurrowDeleteOne) Exec(ctx context.Context) error {
	n, err := bdo.bd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{burrow.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bdo *BurrowDeleteOne) ExecX(ctx context.Context) {
	if err := bdo.Exec(ctx); err != nil {
		panic(err)
	}
}
