// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gophernet/pkg/db/ent/burrow"
	"gophernet/pkg/db/ent/predicate"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeBurrow = "Burrow"
)

// BurrowMutation represents an operation that mutates the Burrow nodes in the graph.
type BurrowMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	depth         *float64
	adddepth      *float64
	width         *float64
	addwidth      *float64
	is_occupied   *bool
	age           *int
	addage        *int
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Burrow, error)
	predicates    []predicate.Burrow
}

var _ ent.Mutation = (*BurrowMutation)(nil)

// burrowOption allows management of the mutation configuration using functional options.
type burrowOption func(*BurrowMutation)

// newBurrowMutation creates new mutation for the Burrow entity.
func newBurrowMutation(c config, op Op, opts ...burrowOption) *BurrowMutation {
	m := &BurrowMutation{
		config:        c,
		op:            op,
		typ:           TypeBurrow,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withBurrowID sets the ID field of the mutation.
func withBurrowID(id int) burrowOption {
	return func(m *BurrowMutation) {
		var (
			err   error
			once  sync.Once
			value *Burrow
		)
		m.oldValue = func(ctx context.Context) (*Burrow, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Burrow.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withBurrow sets the old Burrow of the mutation.
func withBurrow(node *Burrow) burrowOption {
	return func(m *BurrowMutation) {
		m.oldValue = func(context.Context) (*Burrow, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m BurrowMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m BurrowMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Burrow entities.
func (m *BurrowMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *BurrowMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *BurrowMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Burrow.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *BurrowMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *BurrowMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Burrow entity.
// If the Burrow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BurrowMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *BurrowMutation) ResetName() {
	m.name = nil
}

// SetDepth sets the "depth" field.
func (m *BurrowMutation) SetDepth(f float64) {
	m.depth = &f
	m.adddepth = nil
}

// Depth returns the value of the "depth" field in the mutation.
func (m *BurrowMutation) Depth() (r float64, exists bool) {
	v := m.depth
	if v == nil {
		return
	}
	return *v, true
}

// OldDepth returns the old "depth" field's value of the Burrow entity.
// If the Burrow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BurrowMutation) OldDepth(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDepth is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDepth requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDepth: %w", err)
	}
	return oldValue.Depth, nil
}

// AddDepth adds f to the "depth" field.
func (m *BurrowMutation) AddDepth(f float64) {
	if m.adddepth != nil {
		*m.adddepth += f
	} else {
		m.adddepth = &f
	}
}

// AddedDepth returns the value that was added to the "depth" field in this mutation.
func (m *BurrowMutation) AddedDepth() (r float64, exists bool) {
	v := m.adddepth
	if v == nil {
		return
	}
	return *v, true
}

// ResetDepth resets all changes to the "depth" field.
func (m *BurrowMutation) ResetDepth() {
	m.depth = nil
	m.adddepth = nil
}

// SetWidth sets the "width" field.
func (m *BurrowMutation) SetWidth(f float64) {
	m.width = &f
	m.addwidth = nil
}

// Width returns the value of the "width" field in the mutation.
func (m *BurrowMutation) Width() (r float64, exists bool) {
	v := m.width
	if v == nil {
		return
	}
	return *v, true
}

// OldWidth returns the old "width" field's value of the Burrow entity.
// If the Burrow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BurrowMutation) OldWidth(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWidth is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWidth requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWidth: %w", err)
	}
	return oldValue.Width, nil
}

// AddWidth adds f to the "width" field.
func (m *BurrowMutation) AddWidth(f float64) {
	if m.addwidth != nil {
		*m.addwidth += f
	} else {
		m.addwidth = &f
	}
}

// AddedWidth returns the value that was added to the "width" field in this mutation.
func (m *BurrowMutation) AddedWidth() (r float64, exists bool) {
	v := m.addwidth
	if v == nil {
		return
	}
	return *v, true
}

// ResetWidth resets all changes to the "width" field.
func (m *BurrowMutation) ResetWidth() {
	m.width = nil
	m.addwidth = nil
}

// SetIsOccupied sets the "is_occupied" field.
func (m *BurrowMutation) SetIsOccupied(b bool) {
	m.is_occupied = &b
}

// IsOccupied returns the value of the "is_occupied" field in the mutation.
func (m *BurrowMutation) IsOccupied() (r bool, exists bool) {
	v := m.is_occupied
	if v == nil {
		return
	}
	return *v, true
}

// OldIsOccupied returns the old "is_occupied" field's value of the Burrow entity.
// If the Burrow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BurrowMutation) OldIsOccupied(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsOccupied is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsOccupied requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsOccupied: %w", err)
	}
	return oldValue.IsOccupied, nil
}

// ResetIsOccupied resets all changes to the "is_occupied" field.
func (m *BurrowMutation) ResetIsOccupied() {
	m.is_occupied = nil
}

// SetAge sets the "age" field.
func (m *BurrowMutation) SetAge(i int) {
	m.age = &i
	m.addage = nil
}

// Age returns the value of the "age" field in the mutation.
func (m *BurrowMutation) Age() (r int, exists bool) {
	v := m.age
	if v == nil {
		return
	}
	return *v, true
}

// OldAge returns the old "age" field's value of the Burrow entity.
// If the Burrow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BurrowMutation) OldAge(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAge is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAge requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAge: %w", err)
	}
	return oldValue.Age, nil
}

// AddAge adds i to the "age" field.
func (m *BurrowMutation) AddAge(i int) {
	if m.addage != nil {
		*m.addage += i
	} else {
		m.addage = &i
	}
}

// AddedAge returns the value that was added to the "age" field in this mutation.
func (m *BurrowMutation) AddedAge() (r int, exists bool) {
	v := m.addage
	if v == nil {
		return
	}
	return *v, true
}

// ResetAge resets all changes to the "age" field.
func (m *BurrowMutation) ResetAge() {
	m.age = nil
	m.addage = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *BurrowMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *BurrowMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Burrow entity.
// If the Burrow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BurrowMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *BurrowMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the BurrowMutation builder.
func (m *BurrowMutation) Where(ps ...predicate.Burrow) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the BurrowMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *BurrowMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Burrow, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *BurrowMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *BurrowMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Burrow).
func (m *BurrowMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *BurrowMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.name != nil {
		fields = append(fields, burrow.FieldName)
	}
	if m.depth != nil {
		fields = append(fields, burrow.FieldDepth)
	}
	if m.width != nil {
		fields = append(fields, burrow.FieldWidth)
	}
	if m.is_occupied != nil {
		fields = append(fields, burrow.FieldIsOccupied)
	}
	if m.age != nil {
		fields = append(fields, burrow.FieldAge)
	}
	if m.updated_at != nil {
		fields = append(fields, burrow.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *BurrowMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case burrow.FieldName:
		return m.Name()
	case burrow.FieldDepth:
		return m.Depth()
	case burrow.FieldWidth:
		return m.Width()
	case burrow.FieldIsOccupied:
		return m.IsOccupied()
	case burrow.FieldAge:
		return m.Age()
	case burrow.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *BurrowMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case burrow.FieldName:
		return m.OldName(ctx)
	case burrow.FieldDepth:
		return m.OldDepth(ctx)
	case burrow.FieldWidth:
		return m.OldWidth(ctx)
	case burrow.FieldIsOccupied:
		return m.OldIsOccupied(ctx)
	case burrow.FieldAge:
		return m.OldAge(ctx)
	case burrow.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Burrow field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BurrowMutation) SetField(name string, value ent.Value) error {
	switch name {
	case burrow.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case burrow.FieldDepth:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDepth(v)
		return nil
	case burrow.FieldWidth:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWidth(v)
		return nil
	case burrow.FieldIsOccupied:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsOccupied(v)
		return nil
	case burrow.FieldAge:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAge(v)
		return nil
	case burrow.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Burrow field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *BurrowMutation) AddedFields() []string {
	var fields []string
	if m.adddepth != nil {
		fields = append(fields, burrow.FieldDepth)
	}
	if m.addwidth != nil {
		fields = append(fields, burrow.FieldWidth)
	}
	if m.addage != nil {
		fields = append(fields, burrow.FieldAge)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *BurrowMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case burrow.FieldDepth:
		return m.AddedDepth()
	case burrow.FieldWidth:
		return m.AddedWidth()
	case burrow.FieldAge:
		return m.AddedAge()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BurrowMutation) AddField(name string, value ent.Value) error {
	switch name {
	case burrow.FieldDepth:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDepth(v)
		return nil
	case burrow.FieldWidth:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddWidth(v)
		return nil
	case burrow.FieldAge:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAge(v)
		return nil
	}
	return fmt.Errorf("unknown Burrow numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *BurrowMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *BurrowMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *BurrowMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Burrow nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *BurrowMutation) ResetField(name string) error {
	switch name {
	case burrow.FieldName:
		m.ResetName()
		return nil
	case burrow.FieldDepth:
		m.ResetDepth()
		return nil
	case burrow.FieldWidth:
		m.ResetWidth()
		return nil
	case burrow.FieldIsOccupied:
		m.ResetIsOccupied()
		return nil
	case burrow.FieldAge:
		m.ResetAge()
		return nil
	case burrow.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Burrow field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *BurrowMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *BurrowMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *BurrowMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *BurrowMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *BurrowMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *BurrowMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *BurrowMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Burrow unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *BurrowMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Burrow edge %s", name)
}
