// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gophernet/pkg/db/ent/burrow"
	"gophernet/pkg/db/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	burrowFields := schema.Burrow{}.Fields()
	_ = burrowFields
	// burrowDescDepth is the schema descriptor for depth field.
	burrowDescDepth := burrowFields[2].Descriptor()
	// burrow.DefaultDepth holds the default value on creation for the depth field.
	burrow.DefaultDepth = burrowDescDepth.Default.(float64)
	// burrowDescWidth is the schema descriptor for width field.
	burrowDescWidth := burrowFields[3].Descriptor()
	// burrow.DefaultWidth holds the default value on creation for the width field.
	burrow.DefaultWidth = burrowDescWidth.Default.(float64)
	// burrowDescIsOccupied is the schema descriptor for is_occupied field.
	burrowDescIsOccupied := burrowFields[4].Descriptor()
	// burrow.DefaultIsOccupied holds the default value on creation for the is_occupied field.
	burrow.DefaultIsOccupied = burrowDescIsOccupied.Default.(bool)
	// burrowDescID is the schema descriptor for id field.
	burrowDescID := burrowFields[0].Descriptor()
	// burrow.IDValidator is a validator for the "id" field. It is called by the builders before save.
	burrow.IDValidator = burrowDescID.Validators[0].(func(int) error)
}
