definitions:
  models.Burrow:
    properties:
      age:
        type: integer
      depth:
        type: number
      id:
        type: integer
      is_occupied:
        type: boolean
      name:
        type: string
      width:
        type: number
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /burrows/{id}/release:
    post:
      consumes:
      - application/json
      description: Release a burrow by ID
      parameters:
      - description: Burrow ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Burrow'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Release a Burrow
      tags:
      - burrows
  /burrows/{id}/rent:
    post:
      consumes:
      - application/json
      description: Rent a burrow by ID
      parameters:
      - description: Burrow ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Burrow'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Rent a Burrow
      tags:
      - burrows
  /burrows/status:
    get:
      consumes:
      - application/json
      description: Get the status of all burrows
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Burrow'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get Burrow Status
      tags:
      - burrows
  /gopher:
    get:
      consumes:
      - application/json
      description: Get a welcome message from Gopher
      produces:
      - application/json
      responses:
        "200":
          description: Gopher says hi!
          schema:
            type: string
      summary: Get Gopher
      tags:
      - gopher
swagger: "2.0"
